/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    doctors: Doctor;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'clinic-general-information': ClinicGeneralInformation;
    social: Social;
    legal: Legal;
    about: About;
    'patient-information': PatientInformation;
  };
  globalsSelect: {
    'clinic-general-information': ClinicGeneralInformationSelect<false> | ClinicGeneralInformationSelect<true>;
    social: SocialSelect<false> | SocialSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'patient-information': PatientInformationSelect<false> | PatientInformationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  photo?: (number | null) | Media;
  fullName?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  prefix?: ('Dr.' | 'Mr.' | 'Ms.' | 'Mrs.' | 'Nurse') | null;
  title?: string | null;
  specialty?: string | null;
  languages?:
    | {
        language?: string | null;
        id?: string | null;
      }[]
    | null;
  biography?:
    | {
        paragraph?: string | null;
        id?: string | null;
      }[]
    | null;
  education?: string | null;
  qualifications?:
    | {
        Qualification?: string | null;
        id?: string | null;
      }[]
    | null;
  clinicalInterests?:
    | {
        clinicalInterest?: string | null;
        id?: string | null;
      }[]
    | null;
  services?: (number | Service)[] | null;
  profileReviewer?: (number | null) | Doctor;
  reviewDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  image?: (number | null) | Media;
  banner?: (number | null) | Media;
  name?: string | null;
  introduction?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  content?: {
    aboutHeader?: string | null;
    aboutParagraphs?:
      | {
          paragraph?: string | null;
          id?: string | null;
        }[]
      | null;
    aboutImages?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    qualificationsHeader?: string | null;
    qualificationsParagraphs?:
      | {
          paragraph?: string | null;
          id?: string | null;
        }[]
      | null;
    qualifiers?:
      | {
          header?: string | null;
          qualifier?: string | null;
          id?: string | null;
        }[]
      | null;
    qualificationsImages?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    benefitsHeader?: string | null;
    benefits?:
      | {
          header: string;
          benefit: string;
          id?: string | null;
        }[]
      | null;
    video?: (number | null) | Media;
    processHeader?: string | null;
    steps?:
      | {
          header: string;
          step: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    altHeader?: string | null;
    treatments?:
      | {
          header: string;
          treatment: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  FAQs?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  relevantDoctors?: (number | Doctor)[] | null;
  reviewer?: (number | null) | Doctor;
  lastReviewDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  photo?: T;
  fullName?: T;
  generateSlug?: T;
  slug?: T;
  prefix?: T;
  title?: T;
  specialty?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  biography?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  education?: T;
  qualifications?:
    | T
    | {
        Qualification?: T;
        id?: T;
      };
  clinicalInterests?:
    | T
    | {
        clinicalInterest?: T;
        id?: T;
      };
  services?: T;
  profileReviewer?: T;
  reviewDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  image?: T;
  banner?: T;
  name?: T;
  introduction?: T;
  generateSlug?: T;
  slug?: T;
  content?:
    | T
    | {
        aboutHeader?: T;
        aboutParagraphs?:
          | T
          | {
              paragraph?: T;
              id?: T;
            };
        aboutImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        qualificationsHeader?: T;
        qualificationsParagraphs?:
          | T
          | {
              paragraph?: T;
              id?: T;
            };
        qualifiers?:
          | T
          | {
              header?: T;
              qualifier?: T;
              id?: T;
            };
        qualificationsImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        benefitsHeader?: T;
        benefits?:
          | T
          | {
              header?: T;
              benefit?: T;
              id?: T;
            };
        video?: T;
        processHeader?: T;
        steps?:
          | T
          | {
              header?: T;
              step?: T;
              image?: T;
              id?: T;
            };
        altHeader?: T;
        treatments?:
          | T
          | {
              header?: T;
              treatment?: T;
              image?: T;
              id?: T;
            };
      };
  FAQs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relevantDoctors?: T;
  reviewer?: T;
  lastReviewDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-general-information".
 */
export interface ClinicGeneralInformation {
  id: number;
  address?: string | null;
  mapsLink?: string | null;
  phoneNumber?: string | null;
  email?: string | null;
  parkingInformation?: string | null;
  operationHours?: {
    sunday?: {
      openTime?: string | null;
      closeTime?: string | null;
    };
    monday?: {
      openTime?: string | null;
      closeTime?: string | null;
    };
    tuesday?: {
      openTime?: string | null;
      closeTime?: string | null;
    };
    wednesday?: {
      openTime?: string | null;
      closeTime?: string | null;
    };
    thursday?: {
      openTime?: string | null;
      closeTime?: string | null;
    };
    friday?: {
      openTime?: string | null;
      closeTime?: string | null;
    };
    saturday?: {
      openTime?: string | null;
      closeTime?: string | null;
    };
  };
  footerHours?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social".
 */
export interface Social {
  id: number;
  instagram?: string | null;
  facebook?: string | null;
  youtube?: string | null;
  snapchat?: string | null;
  x?: string | null;
  whatsapp?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  privacyPolicy?: string | null;
  tos?: string | null;
  cookiePolicy?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  missionStatement?: string | null;
  ourCenter?: string | null;
  visitors?: number | null;
  expYears?: number | null;
  testimonials?:
    | {
        name?: string | null;
        testimonial?: string | null;
        date?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  laboratory?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-information".
 */
export interface PatientInformation {
  id: number;
  firstVisit?: string | null;
  FAQs?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-general-information_select".
 */
export interface ClinicGeneralInformationSelect<T extends boolean = true> {
  address?: T;
  mapsLink?: T;
  phoneNumber?: T;
  email?: T;
  parkingInformation?: T;
  operationHours?:
    | T
    | {
        sunday?:
          | T
          | {
              openTime?: T;
              closeTime?: T;
            };
        monday?:
          | T
          | {
              openTime?: T;
              closeTime?: T;
            };
        tuesday?:
          | T
          | {
              openTime?: T;
              closeTime?: T;
            };
        wednesday?:
          | T
          | {
              openTime?: T;
              closeTime?: T;
            };
        thursday?:
          | T
          | {
              openTime?: T;
              closeTime?: T;
            };
        friday?:
          | T
          | {
              openTime?: T;
              closeTime?: T;
            };
        saturday?:
          | T
          | {
              openTime?: T;
              closeTime?: T;
            };
      };
  footerHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social_select".
 */
export interface SocialSelect<T extends boolean = true> {
  instagram?: T;
  facebook?: T;
  youtube?: T;
  snapchat?: T;
  x?: T;
  whatsapp?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  privacyPolicy?: T;
  tos?: T;
  cookiePolicy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  missionStatement?: T;
  ourCenter?: T;
  visitors?: T;
  expYears?: T;
  testimonials?:
    | T
    | {
        name?: T;
        testimonial?: T;
        date?: T;
        image?: T;
        id?: T;
      };
  laboratory?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-information_select".
 */
export interface PatientInformationSelect<T extends boolean = true> {
  firstVisit?: T;
  FAQs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}